# ==============================================
#    PerWorldInventory by lukeeey
#    https://github.com/lukeeey/PerWorldInventory
# ==============================================

# Worlds in which inventories should not be bundled.
not-bundled-worlds: !!set
  world: null

ignoreCreativeMode: true
enableBypassPermission: true
